version: '3.4'

services:
  #database:
  #  image:  postgres
  #  container_name: pg_container
  #  restart: always
  #  environment:
  #    POSTGRES_PASSWORD: 123xyz12!
  #  volumes:
  #    - pgdata:/var/lib/postgresql/data

  #sql:
  #  container_name: sql
  #  image: "mcr.microsoft.com/mssql/server"
  #  user: root
  #  environment:
  #    SA_PASSWORD: "123xyz12!"
  #    ACCEPT_EULA: "Y"
  #  ports:
  #    - 1433:1433
  #  volumes:
  #    - sqldata:/var/opt/mssql/data/

  spms.web:
    image: ${DOCKER_REGISTRY-}spmsweb
    build:
      context: .
      dockerfile: SPMS.Web/Dockerfile
    # depends_on:
    #  - sql
    #  - redis_db
    

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    
  
  #redis_db:
  #  image: "redis:alpine"
  #  container_name: redis_db
  #  user: root
  #  hostname: redis_db
  #  command: redis-server #--requirepass 123xyz12!
  #  ports:
  #   - "6379:6379"
  #  volumes:
  #    - redisdata:/var/lib/redis
  #  #  - redisconf:/usr/local/etc/redis/redis.conf
  #  #environment:
  #  # - REDIS_REPLICATION_MODE=master

#volumes:
  #pgdata: {}
  #sqldata: {}
  #redisdata: {}
  #redisconf: {}