apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spms-0-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - spms0.beyond-the-darkness.com
    secretName: spms0-btd-tls
  rules:
  - host: spms0.beyond-the-darkness.com
    http:
      paths:
      - backend:
          serviceName: spms-0
          servicePort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: btd-beyond-the-darkness-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - btd.beyond-the-darkness.com
    secretName: btd-beyond-the-darkness-tls
  rules:

  - host: btd.beyond-the-darkness.com
    http:
      paths:
      - backend: 
          serviceName: spms-0
          servicePort: 80
